#!/usr/bin/env bash
# lane.sh - cross-worktree ATOMIC claim ledger for the parallel build lanes.
#
# WHY THIS EXISTS
#   A git working tree is a PRIVATE view: a claim written into one worktree's
#   feature-dashboard.md is invisible to the sibling worktrees until it is
#   committed, pushed, AND the sibling pulls. That gap is a race window where
#   two lanes pick the SAME item. This ledger removes the race by living OUTSIDE
#   every worktree (a fixed shared path) and using an ATOMIC primitive every
#   lane can see instantly.
#
#   Atomicity: POSIX `mkdir` either creates the dir or fails - never half-does
#   it - so `mkdir claims/<ID>` is a race-free mutex. If two lanes claim the
#   same ID at the same instant, exactly one mkdir wins; the loser gets EEXIST
#   and picks another item. No daemon, no database, no lock library.
#
#   Beyond the per-item mutex, each claim also RESERVES the file globs it will
#   touch. Before a claim is granted, its globs are checked against every other
#   active claim; an overlap is rejected. That generalises the old static
#   file-disjoint lane model to dynamic, roam-the-whole-dashboard picking: two
#   lanes can never hold overlapping files even when they pull different items.
#
# LEDGER LOCATION  ${CADENCE_LEDGER:-$HOME/.cadence-parallel}
#   claims/<ID>/meta   one dir per claimed item; `meta` is key=value lines.
#   LANES.md           human-readable registry (regenerated by `list`).
#
# SUBCOMMANDS
#   lane.sh init
#   lane.sh claim <ID> <lane> "glob1,glob2,..." ["note"]   # exit 0 won, 1 held, 3 file-conflict
#   lane.sh pin   <ID> <lane> "glob1,glob2,..." ["note"]   # like claim but reap-proof (area reservation)
#   lane.sh release <ID>
#   lane.sh heartbeat <ID>                                  # keep a long build's claim fresh
#   lane.sh list                                            # all active claims
#   lane.sh board                                           # per-lane view: Lane 0..4 -> current item
#   lane.sh mine <lane>                                     # this lane's active claims
#   lane.sh held <ID>                                       # print holder line if claimed, else nothing
#   lane.sh reap [ttl_hours]                                # auto-release UNPINNED claims older than ttl (default 6h)
#
# EXIT CODES (claim):  0 = claimed, 1 = already held by someone, 3 = file-glob conflict
set -uo pipefail

LEDGER="${CADENCE_LEDGER:-$HOME/.cadence-parallel}"
CLAIMS="$LEDGER/claims"

# DONE registry: the ledger remembers recently-COMPLETED items (not just active claims),
# so `claim` REFUSES an item another lane already finished - the mechanical fix so two
# sessions never re-pick the same done work. `lane.sh done <ID>` records a completion;
# `reap` prunes old markers (by then the ✅ is in the register, caught by `git pull`).
DONE="$LEDGER/done"
_sync_board() { :; }   # retired 2026-06-21: status lives in feature-dashboard.md, not a separate file

_now() { date +%s; }
_die() { echo "lane.sh: $*" >&2; exit 2; }

_ensure() { mkdir -p "$CLAIMS" 2>/dev/null || true; }

# meta is simple key=value lines so it parses with no jq dependency.
_meta_get() { # <claimdir> <key>
  local f="$1/meta" k="$2"
  [ -f "$f" ] || return 1
  sed -n "s/^$k=//p" "$f" | head -1
}

# Reduce a glob to its literal directory/prefix (everything before the first
# wildcard), trailing slash stripped. `src/lib/incidents*.ts` -> `src/lib/incidents`
_glob_prefix() {
  local g="$1"
  g="${g%%\**}"   # cut at first *
  g="${g%%\?*}"   # cut at first ?
  g="${g%/}"
  printf '%s' "$g"
}

# 0 (true) if globs A and B can touch the same path. Conservative: a bare
# wildcard (empty prefix) overlaps everything.
_globs_overlap() { # <csvA> <csvB>
  local a b pa pb
  IFS=',' read -ra _A <<< "$1"
  IFS=',' read -ra _B <<< "$2"
  for a in "${_A[@]}"; do
    a="${a# }"; a="${a% }"; [ -z "$a" ] && continue
    pa="$(_glob_prefix "$a")"
    for b in "${_B[@]}"; do
      b="${b# }"; b="${b% }"; [ -z "$b" ] && continue
      pb="$(_glob_prefix "$b")"
      if [ -z "$pa" ] || [ -z "$pb" ]; then return 0; fi   # bare * -> overlaps all
      case "$pa" in "$pb"*) return 0;; esac
      case "$pb" in "$pa"*) return 0;; esac
    done
  done
  return 1
}

cmd_init() { _ensure; echo "ledger ready at $LEDGER"; }

cmd_claim() {
  local id="${1:-}" lane="${2:-}" globs="${3:-}" note="${4:-}"
  [ -n "$id" ] && [ -n "$lane" ] || _die "usage: claim <ID> <lane> \"globs\" [note]"
  _ensure
  local dir="$CLAIMS/$id"

  # 0) already COMPLETED by another lane? refuse - do NOT redo finished work.
  if [ -e "$DONE/$id" ]; then
    echo "DONE $id (already completed: $(cat "$DONE/$id" 2>/dev/null)); pick another item"
    return 4
  fi

  # 1) atomic per-item mutex
  if ! mkdir "$dir" 2>/dev/null; then
    local h; h="$(_meta_get "$dir" lane 2>/dev/null || echo '?')"
    echo "HELD $id by lane $h (since $(_meta_get "$dir" started 2>/dev/null))"
    return 1
  fi

  # 2) file-glob reservation: reject if my globs overlap ANOTHER LANE's active claim.
  #    A lane never conflicts with its own claims/reservations (one lane = one
  #    worker, building one item at a time; its area-reservation must not block
  #    its own per-item claim). So overlap is only checked across DIFFERENT lanes.
  if [ -n "$globs" ]; then
    local other og ol oid
    for other in "$CLAIMS"/*/; do
      [ -d "$other" ] || continue
      [ "$other" = "$dir/" ] && continue
      ol="$(_meta_get "${other%/}" lane 2>/dev/null || echo '?')"
      [ "$ol" = "$lane" ] && continue                 # same lane -> never a conflict
      og="$(_meta_get "${other%/}" globs 2>/dev/null || true)"
      [ -n "$og" ] || continue
      if _globs_overlap "$globs" "$og"; then
        oid="$(basename "${other%/}")"
        rmdir "$dir" 2>/dev/null || rm -rf "$dir"     # back out my just-won mutex
        echo "CONFLICT $id globs overlap lane $ol's claim $oid ($og)"
        return 3
      fi
    done
  fi

  # 3) record meta
  local ts; ts="$(_now)"
  {
    echo "id=$id"
    echo "lane=$lane"
    echo "globs=$globs"
    echo "note=$note"
    echo "pinned=${PINNED:-false}"
    echo "pid=$$"
    echo "host=$(hostname 2>/dev/null || echo unknown)"
    echo "started=$(date '+%Y-%m-%d %H:%M:%S' 2>/dev/null)"
    echo "epoch=$ts"
    echo "beat=$ts"
  } > "$dir/meta"
  [ "${PINNED:-false}" = "true" ] && echo "PINNED $id by lane $lane" || echo "CLAIMED $id by lane $lane"
  _sync_board
  return 0
}

cmd_pin() { PINNED=true cmd_claim "$@"; }

cmd_release() {
  local id="${1:-}"; [ -n "$id" ] || _die "usage: release <ID>"
  local dir="$CLAIMS/$id"
  if [ -d "$dir" ]; then rm -rf "$dir"; echo "RELEASED $id"; else echo "not held: $id"; fi
}

# `done <ID>`: mark an item fully COMPLETED (✅). Frees the active claim AND records a DONE
# marker so no other lane re-picks it. Call this only on a true ✅ completion; a ◐ partial
# uses `release` instead (it stays re-pickable so a later lane can continue the remainder).
cmd_done() {
  local id="${1:-}"; [ -n "$id" ] || _die "usage: done <ID>"
  _ensure; mkdir -p "$DONE"
  rm -rf "${CLAIMS:?}/$id" 2>/dev/null || true
  echo "$(date '+%Y-%m-%d %H:%M:%S' 2>/dev/null) lane=${2:-?}" > "$DONE/$id"
  echo "DONE-RECORDED $id (claim freed; future claims refused)"
}

# `next [count]`: DETERMINISTICALLY print the next eligible item IDs (lowest Rank first) -
# this is "what to build next" with ZERO judgment. Eligible = register status ⬜ or ◐
# (a ◐ is partial = it HAS remaining work, so it is ALWAYS continue-able, never "skip as
# done") AND priority is an autonomous tier (Tier 1 or Tier 3; Tier 2 design + Tier 4 polish
# are founder-prompted) AND not currently claimed AND not in the DONE registry. The lane runs
# `for id in $(lane.sh next); do lane.sh claim "$id" <lane> "<globs>" && build && break; done`.
# Empty output (exit 2) = the board is GENUINELY dry; anything else means build it, never long-poll.
cmd_next() {
  local count="${1:-500}" reg rank id n=0   # effectively the full eligible list (claim down it until one wins)
  _ensure
  reg="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." 2>/dev/null && pwd)/docs/planning/feature-dashboard.md"
  [ -f "$reg" ] || { echo "register not found: $reg" >&2; return 1; }
  while IFS=$'\t' read -r rank id; do
    [ -d "$CLAIMS/$id" ] && continue        # already claimed by a lane
    [ -e "$DONE/$id" ] && continue          # already completed (no re-pick)
    echo "$id"
    n=$((n + 1)); [ "$n" -ge "$count" ] && break
  done < <(awk -F'|' '
    /^\| [0-9]+ \|/{
      r=$2; s=$3; id=$4; pr=$8;
      gsub(/^[ \t]+|[ \t]+$/,"",r); gsub(/^[ \t]+|[ \t]+$/,"",s); gsub(/^[ \t]+|[ \t]+$/,"",id); gsub(/^[ \t]+|[ \t]+$/,"",pr);
      if ((s=="\342\254\234" || s=="\342\227\220") && (pr=="Tier 1" || pr=="Tier 3")) printf "%d\t%s\n", r, id;
    }' "$reg" | sort -n)
  if [ "$n" = 0 ]; then echo "BOARD DRY: no eligible Tier-1/Tier-3 ⬜/◐ item unclaimed + not done" >&2; return 2; fi
  return 0
}

cmd_heartbeat() {
  local id="${1:-}"; [ -n "$id" ] || _die "usage: heartbeat <ID>"
  local f="$CLAIMS/$id/meta"
  [ -f "$f" ] || { echo "not held: $id"; return 1; }
  local ts; ts="$(_now)"
  if grep -q '^beat=' "$f"; then
    sed -i.bak "s/^beat=.*/beat=$ts/" "$f" && rm -f "$f.bak"
  else
    echo "beat=$ts" >> "$f"
  fi
  echo "beat $id"
}

cmd_held() {
  local id="${1:-}"; [ -n "$id" ] || _die "usage: held <ID>"
  local dir="$CLAIMS/$id"
  [ -d "$dir" ] || return 0
  echo "$id lane=$(_meta_get "$dir" lane) globs=$(_meta_get "$dir" globs) since=$(_meta_get "$dir" started)"
}

_print_claims() { # <lane-filter-or-empty>
  local filter="${1:-}" dir id lane globs started beat now age any=0
  now="$(_now)"
  for dir in "$CLAIMS"/*/; do
    [ -d "$dir" ] || continue
    id="$(basename "${dir%/}")"
    lane="$(_meta_get "${dir%/}" lane)"
    [ -n "$filter" ] && [ "$lane" != "$filter" ] && continue
    globs="$(_meta_get "${dir%/}" globs)"
    started="$(_meta_get "${dir%/}" started)"
    beat="$(_meta_get "${dir%/}" beat)"; [ -n "$beat" ] || beat="$(_meta_get "${dir%/}" epoch)"
    age="?"; [ -n "$beat" ] && age="$(( (now - beat) / 60 ))m"
    local pin=""; [ "$(_meta_get "${dir%/}" pinned)" = "true" ] && pin=" [pinned]"
    printf '  %-22s lane=%-3s age=%-6s globs=%s%s\n' "$id" "${lane:-?}" "$age" "${globs:-<none>}" "$pin"
    any=1
  done
  if [ "$any" = 0 ]; then echo "  (no active claims)"; fi
  return 0
}

cmd_board() { # per-lane "who is building what right now"
  _ensure
  echo "Parallel build board (live @ $LEDGER):"
  local n dir item lane pinned found now beat age
  now="$(_now)"
  for n in 0 1 2 3 4; do
    found=""
    for dir in "$CLAIMS"/*/; do
      [ -d "$dir" ] || continue
      [ "$(_meta_get "${dir%/}" lane)" = "$n" ] || continue
      [ "$(_meta_get "${dir%/}" pinned)" = "true" ] && continue   # area reservations are not a "task"
      beat="$(_meta_get "${dir%/}" beat)"; [ -n "$beat" ] || beat="$(_meta_get "${dir%/}" epoch)"
      age=""; [ -n "$beat" ] && age=" ($(( (now - beat)/60 ))m)"
      found="$found $(basename "${dir%/}")${age}"
    done
    printf '  Lane %s: %s\n' "$n" "${found:-(idle / no active claim)}"
  done
  local anyres=0
  for dir in "$CLAIMS"/*/; do
    [ -d "$dir" ] || continue
    [ "$(_meta_get "${dir%/}" pinned)" = "true" ] || continue
    [ "$anyres" = 0 ] && { echo "  --- standing reservations (safety, not a lane task) ---"; anyres=1; }
    printf '  [reserved] %-12s lane=%s\n' "$(basename "${dir%/}")" "$(_meta_get "${dir%/}" lane)"
  done
  return 0
}

cmd_list() { echo "Active claims @ $LEDGER:"; _ensure; _print_claims ""; }
cmd_mine() { local lane="${1:-}"; [ -n "$lane" ] || _die "usage: mine <lane>"; echo "Lane $lane claims:"; _ensure; _print_claims "$lane"; }

cmd_reap() {
  local ttl_h="${1:-6}" ttl_s dir beat now id
  ttl_s=$(( ttl_h * 3600 )); now="$(_now)"; _ensure
  for dir in "$CLAIMS"/*/; do
    [ -d "$dir" ] || continue
    id="$(basename "${dir%/}")"
    [ "$(_meta_get "${dir%/}" pinned)" = "true" ] && continue   # reservations never expire
    beat="$(_meta_get "${dir%/}" beat)"; [ -n "$beat" ] || beat="$(_meta_get "${dir%/}" epoch)"
    [ -n "$beat" ] || continue
    if [ "$(( now - beat ))" -gt "$ttl_s" ]; then
      rm -rf "$dir"; echo "REAPED $id (stale > ${ttl_h}h)"
    fi
  done
  # prune DONE markers older than 48h (by then the ✅ is in the register, caught by git pull)
  if [ -d "$DONE" ]; then
    find "$DONE" -type f -mmin +2880 -delete 2>/dev/null || true
  fi
}

sub="${1:-}"; shift || true
case "$sub" in
  init)      cmd_init "$@" ;;
  claim)     cmd_claim "$@" ;;
  pin)       cmd_pin "$@" ;;
  release)   cmd_release "$@" ;;
  done)      cmd_done "$@" ;;
  next)      cmd_next "$@" ;;
  heartbeat) cmd_heartbeat "$@" ;;
  list)      cmd_list "$@" ;;
  board)     cmd_board "$@" ;;
  mine)      cmd_mine "$@" ;;
  held)      cmd_held "$@" ;;
  reap)      cmd_reap "$@" ;;
  ""|-h|--help|help)
    sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//' ;;
  *) _die "unknown subcommand: $sub (try: init|claim|release|heartbeat|list|mine|held|reap)" ;;
esac
