#!/usr/bin/env bash
# lane.sh - cross-worktree ATOMIC claim ledger for the parallel build lanes.
#
# WHY THIS EXISTS
#   A git working tree is a PRIVATE view: a claim written into one worktree's
#   feature-dashboard.md is invisible to the sibling worktrees until it is
#   committed, pushed, AND the sibling pulls. That gap is a race window where
#   two lanes pick the SAME item. This ledger removes the race by living OUTSIDE
#   every worktree (a fixed shared path) and using an ATOMIC primitive every
#   lane can see instantly.
#
#   Atomicity: POSIX `mkdir` either creates the dir or fails - never half-does
#   it - so `mkdir claims/<ID>` is a race-free mutex. If two lanes claim the
#   same ID at the same instant, exactly one mkdir wins; the loser gets EEXIST
#   and picks another item. No daemon, no database, no lock library.
#
#   Beyond the per-item mutex, each claim also RESERVES the file globs it will
#   touch. Before a claim is granted, its globs are checked against every other
#   active claim; an overlap is rejected. That generalises the old static
#   file-disjoint lane model to dynamic, roam-the-whole-dashboard picking: two
#   lanes can never hold overlapping files even when they pull different items.
#
# LEDGER LOCATION  ${CADENCE_LEDGER:-$HOME/.cadence-parallel}
#   claims/<ID>/meta   one dir per claimed item; `meta` is key=value lines.
#   LANES.md           human-readable registry (regenerated by `list`).
#
# SUBCOMMANDS
#   lane.sh init
#   lane.sh claim <ID> <lane> "glob1,glob2,..." ["note"]   # exit 0 won, 1 held, 3 file-conflict
#   lane.sh pin   <ID> <lane> "glob1,glob2,..." ["note"]   # like claim but reap-proof (area reservation)
#   lane.sh release <ID>
#   lane.sh heartbeat <ID>                                  # keep a long build's claim fresh
#   lane.sh list                                            # all active claims
#   lane.sh mine <lane>                                     # this lane's active claims
#   lane.sh held <ID>                                       # print holder line if claimed, else nothing
#   lane.sh reap [ttl_hours]                                # auto-release UNPINNED claims older than ttl (default 6h)
#
# EXIT CODES (claim):  0 = claimed, 1 = already held by someone, 3 = file-glob conflict
set -uo pipefail

LEDGER="${CADENCE_LEDGER:-$HOME/.cadence-parallel}"
CLAIMS="$LEDGER/claims"

_now() { date +%s; }
_die() { echo "lane.sh: $*" >&2; exit 2; }

_ensure() { mkdir -p "$CLAIMS" 2>/dev/null || true; }

# meta is simple key=value lines so it parses with no jq dependency.
_meta_get() { # <claimdir> <key>
  local f="$1/meta" k="$2"
  [ -f "$f" ] || return 1
  sed -n "s/^$k=//p" "$f" | head -1
}

# Reduce a glob to its literal directory/prefix (everything before the first
# wildcard), trailing slash stripped. `src/lib/incidents*.ts` -> `src/lib/incidents`
_glob_prefix() {
  local g="$1"
  g="${g%%\**}"   # cut at first *
  g="${g%%\?*}"   # cut at first ?
  g="${g%/}"
  printf '%s' "$g"
}

# 0 (true) if globs A and B can touch the same path. Conservative: a bare
# wildcard (empty prefix) overlaps everything.
_globs_overlap() { # <csvA> <csvB>
  local a b pa pb
  IFS=',' read -ra _A <<< "$1"
  IFS=',' read -ra _B <<< "$2"
  for a in "${_A[@]}"; do
    a="${a# }"; a="${a% }"; [ -z "$a" ] && continue
    pa="$(_glob_prefix "$a")"
    for b in "${_B[@]}"; do
      b="${b# }"; b="${b% }"; [ -z "$b" ] && continue
      pb="$(_glob_prefix "$b")"
      if [ -z "$pa" ] || [ -z "$pb" ]; then return 0; fi   # bare * -> overlaps all
      case "$pa" in "$pb"*) return 0;; esac
      case "$pb" in "$pa"*) return 0;; esac
    done
  done
  return 1
}

cmd_init() { _ensure; echo "ledger ready at $LEDGER"; }

cmd_claim() {
  local id="${1:-}" lane="${2:-}" globs="${3:-}" note="${4:-}"
  [ -n "$id" ] && [ -n "$lane" ] || _die "usage: claim <ID> <lane> \"globs\" [note]"
  _ensure
  local dir="$CLAIMS/$id"

  # 1) atomic per-item mutex
  if ! mkdir "$dir" 2>/dev/null; then
    local h; h="$(_meta_get "$dir" lane 2>/dev/null || echo '?')"
    echo "HELD $id by lane $h (since $(_meta_get "$dir" started 2>/dev/null))"
    return 1
  fi

  # 2) file-glob reservation: reject if my globs overlap ANOTHER LANE's active claim.
  #    A lane never conflicts with its own claims/reservations (one lane = one
  #    worker, building one item at a time; its area-reservation must not block
  #    its own per-item claim). So overlap is only checked across DIFFERENT lanes.
  if [ -n "$globs" ]; then
    local other og ol oid
    for other in "$CLAIMS"/*/; do
      [ -d "$other" ] || continue
      [ "$other" = "$dir/" ] && continue
      ol="$(_meta_get "${other%/}" lane 2>/dev/null || echo '?')"
      [ "$ol" = "$lane" ] && continue                 # same lane -> never a conflict
      og="$(_meta_get "${other%/}" globs 2>/dev/null || true)"
      [ -n "$og" ] || continue
      if _globs_overlap "$globs" "$og"; then
        oid="$(basename "${other%/}")"
        rmdir "$dir" 2>/dev/null || rm -rf "$dir"     # back out my just-won mutex
        echo "CONFLICT $id globs overlap lane $ol's claim $oid ($og)"
        return 3
      fi
    done
  fi

  # 3) record meta
  local ts; ts="$(_now)"
  {
    echo "id=$id"
    echo "lane=$lane"
    echo "globs=$globs"
    echo "note=$note"
    echo "pinned=${PINNED:-false}"
    echo "pid=$$"
    echo "host=$(hostname 2>/dev/null || echo unknown)"
    echo "started=$(date '+%Y-%m-%d %H:%M:%S' 2>/dev/null)"
    echo "epoch=$ts"
    echo "beat=$ts"
  } > "$dir/meta"
  [ "${PINNED:-false}" = "true" ] && echo "PINNED $id by lane $lane" || echo "CLAIMED $id by lane $lane"
  return 0
}

cmd_pin() { PINNED=true cmd_claim "$@"; }

cmd_release() {
  local id="${1:-}"; [ -n "$id" ] || _die "usage: release <ID>"
  local dir="$CLAIMS/$id"
  if [ -d "$dir" ]; then rm -rf "$dir"; echo "RELEASED $id"; else echo "not held: $id"; fi
}

cmd_heartbeat() {
  local id="${1:-}"; [ -n "$id" ] || _die "usage: heartbeat <ID>"
  local f="$CLAIMS/$id/meta"
  [ -f "$f" ] || { echo "not held: $id"; return 1; }
  local ts; ts="$(_now)"
  if grep -q '^beat=' "$f"; then
    sed -i.bak "s/^beat=.*/beat=$ts/" "$f" && rm -f "$f.bak"
  else
    echo "beat=$ts" >> "$f"
  fi
  echo "beat $id"
}

cmd_held() {
  local id="${1:-}"; [ -n "$id" ] || _die "usage: held <ID>"
  local dir="$CLAIMS/$id"
  [ -d "$dir" ] || return 0
  echo "$id lane=$(_meta_get "$dir" lane) globs=$(_meta_get "$dir" globs) since=$(_meta_get "$dir" started)"
}

_print_claims() { # <lane-filter-or-empty>
  local filter="${1:-}" dir id lane globs started beat now age any=0
  now="$(_now)"
  for dir in "$CLAIMS"/*/; do
    [ -d "$dir" ] || continue
    id="$(basename "${dir%/}")"
    lane="$(_meta_get "${dir%/}" lane)"
    [ -n "$filter" ] && [ "$lane" != "$filter" ] && continue
    globs="$(_meta_get "${dir%/}" globs)"
    started="$(_meta_get "${dir%/}" started)"
    beat="$(_meta_get "${dir%/}" beat)"; [ -n "$beat" ] || beat="$(_meta_get "${dir%/}" epoch)"
    age="?"; [ -n "$beat" ] && age="$(( (now - beat) / 60 ))m"
    local pin=""; [ "$(_meta_get "${dir%/}" pinned)" = "true" ] && pin=" [pinned]"
    printf '  %-22s lane=%-3s age=%-6s globs=%s%s\n' "$id" "${lane:-?}" "$age" "${globs:-<none>}" "$pin"
    any=1
  done
  if [ "$any" = 0 ]; then echo "  (no active claims)"; fi
  return 0
}

cmd_list() { echo "Active claims @ $LEDGER:"; _ensure; _print_claims ""; }
cmd_mine() { local lane="${1:-}"; [ -n "$lane" ] || _die "usage: mine <lane>"; echo "Lane $lane claims:"; _ensure; _print_claims "$lane"; }

cmd_reap() {
  local ttl_h="${1:-6}" ttl_s dir beat now id
  ttl_s=$(( ttl_h * 3600 )); now="$(_now)"; _ensure
  for dir in "$CLAIMS"/*/; do
    [ -d "$dir" ] || continue
    id="$(basename "${dir%/}")"
    [ "$(_meta_get "${dir%/}" pinned)" = "true" ] && continue   # reservations never expire
    beat="$(_meta_get "${dir%/}" beat)"; [ -n "$beat" ] || beat="$(_meta_get "${dir%/}" epoch)"
    [ -n "$beat" ] || continue
    if [ "$(( now - beat ))" -gt "$ttl_s" ]; then
      rm -rf "$dir"; echo "REAPED $id (stale > ${ttl_h}h)"
    fi
  done
}

sub="${1:-}"; shift || true
case "$sub" in
  init)      cmd_init "$@" ;;
  claim)     cmd_claim "$@" ;;
  pin)       cmd_pin "$@" ;;
  release)   cmd_release "$@" ;;
  heartbeat) cmd_heartbeat "$@" ;;
  list)      cmd_list "$@" ;;
  mine)      cmd_mine "$@" ;;
  held)      cmd_held "$@" ;;
  reap)      cmd_reap "$@" ;;
  ""|-h|--help|help)
    sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//' ;;
  *) _die "unknown subcommand: $sub (try: init|claim|release|heartbeat|list|mine|held|reap)" ;;
esac
