// This file is automatically generated. Do not edit it directly.
import type { AnyFunctionMiddleware } from "@tanstack/start-client-core";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = {
  "~types": undefined,
  options: {
    type: "function",
    client: async ({ next }: { next: (ctx?: { headers?: HeadersInit }) => Promise<unknown> }) => {
      const { data } = await supabase.auth.getSession();
      const token = data.session?.access_token;
      return next({
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
    },
  },
} as unknown as AnyFunctionMiddleware;
